---
title: "RADseq base"
subtitle: "Mouse GBS initial steps"
author: "Lucas A. Nell"
date: "May 31, 2016"
output:
  html_document:
    highlight: haddock
    theme: default
  pdf_document:
    highlight: haddock
    latex_engine: xelatex
geometry: margin=1in
fontsize: 12pt
mainfont: Helvetica
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```



# Update

As of June 2016, this is no longer the most updated version. See 
[here](https://github.com/lucasnell/musGBS/blob/master/initial_processing.md)
for newer instructions.

(I've left the old code commented below, so to view it, look at the "Raw" version of this
file on GitHub.)



<!---
# Demultiplex

I used `process_radtags` from [Stacks](http://catchenlab.life.illinois.edu/stacks/).

```{r demx, engine = 'bash'}
# Path to fastq files that need demultiplexed
cd /path/to/fastq

# Run number
export runNum=132571

# Restriction enzyme (we're using GBS so only have one)
export rEnz=apeKI

# Path to Stacks' `process_radtags` file (this will change depending on system)
export process_radtags=/usr/local/apps/stacks/latest/bin/process_radtags
# Tab-delimited text file with 3' barcode, 5' barcode reverse complement, and sample name
export barcodes=musGBS_${runNum}_bc.txt

# Files to demultiplex
export readOne=musGBS_${runNum}_1.fastq.gz
export readTwo=musGBS_${runNum}_2.fastq.gz

# Log output
export logFile=demultiplex_${runNum}.log

# Make "indiv" folder if it doesn't already exist
if [ ! -d "indiv" ]; then
    mkdir indiv
fi

# Now run
${process_radtags} \
    -1 ${readOne} \
    -2 ${readTwo} \
    -b ${barcodes} \
    -o ./indiv/ \
    --inline_inline --disable_rad_check \
    -e ${rEnz} \
    -r -i gzfastq &> ${logFile}
```

# Housekeeping


## File renaming

> File renaming was only done to conform to other fastq files in my directory. This is
> unnecessary if you don't mind the *.1.fq.gz *.2.fq.gz naming from Stacks.

```{r housekeeping, engine = 'bash'}
cd /path/to/fastq/indiv

for f in *.fq.gz
do
    g=`echo ${f/%.fq.gz/} | sed 's/.1$/_1/g; s/.2$/_2/g'`.fastq.gz
    mv $f $g
done
```



## Read renaming

Because `process_radtags` adds "_2" to the end of read names in the R2 files, I'm going
to change them to match the read names in the R1 files. 
If you want to keep the old R2 files with the original `process_radtags` names, change
`--in-place` to `--in-place=_TMP` to make backup files with the suffix `"_TMP"`.

> Because of the uncompressing and re-compressing, this can take a while.

```{r houskeeping_2, engine = 'bash'}
for f in *_2.fastq.gz
do
    gunzip $f
    sed --in-place 's/_2$/_1/g' ${f/%.gz/}
    gzip ${f/%.gz/}
done
```

# Aligning

Aligning was done using `bowtie2`, the same as for DNAseq data. See `basic_DNA-seq.Rmd`
for details.


-->

